-- Generated from activity-entitlements.json. Run after subscription.sql.
insert into public.activity_entitlements (activity_id, access_tier, title, path, category) values
('game/ai-robot-mission','premium','AI Robot Mission','/games/ai-robot-mission/','game'),
('game/algebra-codebreaker','premium','Algebra Codebreaker','/games/algebra-codebreaker/','game'),
('game/angle-detective','premium','Angle Detective','/games/angle-detective/','game'),
('game/balloon-number-pop','premium','Balloon Number Pop','/games/balloon-number-pop/','game'),
('game/clock-tower-junior','premium','Clock Tower Junior','/games/clock-tower-junior/','game'),
('game/colour-pattern-train','premium','Colour Pattern Train','/games/colour-pattern-train/','game'),
('game/coordinate-quest','premium','Coordinate Quest','/games/coordinate-quest/','game'),
('game/crypt-of-equation','premium','Crypt of Equation','/games/crypt-of-equation/','game'),
('game/equation-balance-lab','premium','Equation Balance Lab','/games/equation-balance-lab/','game'),
('game/escape_room_mathematics_year6','premium','Year 6 Mathematics Escape Room','/games/escape_room_mathematics_year6.html','game'),
('game/escape-room-mathematics-year1','premium','Year 1 Mathematics Escape Room','/games/escape-room-mathematics-year1/','game'),
('game/escape-room-mathematics-year2','premium','Year 2 Mathematics Escape Room','/games/escape-room-mathematics-year2/','game'),
('game/escape-room-mathematics-year3','premium','Year 3 Mathematics Escape Room','/games/escape-room-mathematics-year3/','game'),
('game/escape-room-mathematics-year4','premium','Year 4 Mathematics Escape Room','/games/escape-room-mathematics-year4/','game'),
('game/escape-room-mathematics-year5','premium','Year 5 Mathematics Escape Room','/games/escape-room-mathematics-year5/','game'),
('game/exponent-power-up','premium','Exponent Power-Up','/games/exponent-power-up/','game'),
('game/factor-factory','premium','Factor Factory','/games/factor-factory/','game'),
('game/feed-hungry-monster','premium','Feed the Hungry Monster','/games/feed-hungry-monster/','game'),
('game/financial-math-tycoon','premium','Financial Math Tycoon','/games/financial-math-tycoon/','game'),
('game/formula-racing-champion','premium','Formula Racing Champion','/games/formula-racing-champion/','game'),
('game/formula-racing-champion-3d','free','Formula Racing Champion 3D','/games/formula-racing-champion-3d/','game'),
('game/formula-racing-championship','premium','Formula Racing Championship','/games/formula-racing-championship/','game'),
('game/fraction-lab','premium','Fraction Lab','/games/fraction-lab/','game'),
('game/fraction-pizza-party','premium','Fraction Pizza Party','/games/fraction-pizza-party/','game'),
('game/geometry-architect','premium','Geometry Architect','/games/geometry-architect/','game'),
('game/integer-ice-climb','premium','Integer Ice Climb','/games/integer-ice-climb/','game'),
('game/integrated-stem-programs','premium','STEM Discovery Academy','/games/integrated-stem-programs/','game'),
('game/integrated-stem-programs-11-20','premium','STEM Innovation Academy','/games/integrated-stem-programs-11-20/','game'),
('game/kakuro','premium','MathToolsHub Kakuro','/games/kakuro/','game'),
('game/kenken','premium','MathToolsHub KenKen','/games/kenken/','game'),
('game/linear-graph-flight','premium','Linear Graph Flight','/games/linear-graph-flight/','game'),
('game/logic-puzzles','premium','MathToolsHub Logic Puzzles','/games/logic-puzzles/','game'),
('game/mathcity-builder','premium','MathCity Builder','/games/mathcity-builder/','game'),
('game/math-crush','free','CJMath EquaGems','/games/math-crush/','game'),
('game/math-detective-academy','premium','Math Detective Academy','/games/math-detective-academy/','game'),
('game/math-fishing-adventure','premium','Math Fishing Adventure','/games/math-fishing-adventure/','game'),
('game/math-kingdom-defender','premium','Math Kingdom Defender','/games/math-kingdom-defender/','game'),
('game/math-learning-games-21-30','premium','Math Learning Games 21â€“30','/games/math-learning-games-21-30/','game'),
('game/math-learning-games-31-40','premium','SPM Mathematics & Additional Mathematics Games 31â€“40','/games/math-learning-games-31-40/','game'),
('game/math-space-mission','premium','Math Space Mission','/games/math-space-mission/','game'),
('game/measurement-kitchen','premium','Measurement Kitchen','/games/measurement-kitchen/','game'),
('game/money-market-kids','premium','Money Market Kids','/games/money-market-kids/','game'),
('game/nation-builder','premium','Nation Builder','/games/nation-builder/','game'),
('game/number-safari','free','Number Safari','/games/number-safari/','game'),
('game/percentage-market','premium','Percentage Market','/games/percentage-market/','game'),
('game/preschool_interactive_cartoon','premium','Preschool Interactive Cartoon','/games/preschool_interactive_cartoon.html','game'),
('game/probability-carnival','premium','Probability Carnival','/games/probability-carnival/','game'),
('game/pythagoras-rescue','premium','Pythagoras Rescue','/games/pythagoras-rescue/','game'),
('game/ratio-racer','premium','Ratio Racer','/games/ratio-racer/','game'),
('game/sabah-football-championship','premium','Sabah Football Championship','/games/sabah-football-championship/','game'),
('game/sabah-football-manager','premium','Sabah Football Manager','/games/sabah-football-manager/','game'),
('game/sabah-navigator','premium','Sabah Navigator','/games/sabah-navigator/','game'),
('game/school-management-simulator','premium','School Management Simulator','/games/school-management-simulator/','game'),
('game/secondary-math-missions','premium','Form 1 Math Detective Academy','/games/secondary-math-missions/','game'),
('game/sequence-signal','premium','Sequence Signal','/games/sequence-signal/','game'),
('game/shape-builder-town','free','Shape Builder Town','/games/shape-builder-town/','game'),
('game/speed-distance-rally','premium','Speed Distance Rally','/games/speed-distance-rally/','game'),
('game/statistics-stadium','premium','Statistics Stadium','/games/statistics-stadium/','game'),
('game/sudoku','free','MathToolsHub Sudoku','/games/sudoku/','game'),
('game/transformation-portal','premium','Transformation Portal','/games/transformation-portal/','game'),
('game/treasure-hunter','premium','Treasure Hunter','/games/treasure-hunter/','game'),
('game/trigonometry-tower','premium','Trigonometry Tower','/games/trigonometry-tower/','game'),
('game/wild-hunt-safari','free','Wild Hunt Safari','/games/wild-hunt-safari/','game'),
('programme/ai-ethics-and-society-forum','premium','AI Ethics and Society Forum','/learning-programs/catalogue-2/programs/ai-ethics-and-society-forum.html','programme'),
('programme/career-salary-planner','premium','Future Career & Salary Planner','/learning-programs/programs/career-salary-planner.html','programme'),
('programme/chemistry-in-everyday-life-lab','premium','Chemistry in Everyday Life Lab','/learning-programs/catalogue-2/programs/chemistry-in-everyday-life-lab.html','programme'),
('programme/civic-decision-lab','premium','Civic Decision Lab','/learning-programs/catalogue-2/programs/civic-decision-lab.html','programme'),
('programme/climate-adaptation-city-planner','premium','Climate Adaptation City Planner','/learning-programs/catalogue-2/programs/climate-adaptation-city-planner.html','programme'),
('programme/clock-calendar-adventure','premium','Time Travellers: Clock & Calendar Quest','/learning-programs/programs/clock-calendar-adventure.html','programme'),
('programme/community-helpers-mission','premium','Community Helpers Mission','/learning-programs/catalogue-2/programs/community-helpers-mission.html','programme'),
('programme/consumer-finance-studio','premium','MoneyWise Consumer Finance Studio','/learning-programs/programs/consumer-finance-studio.html','programme'),
('programme/cyber-safety-operations-centre','premium','Cyber Safety Operations Centre','/learning-programs/catalogue-2/programs/cyber-safety-operations-centre.html','programme'),
('programme/digital-storytelling-studio','premium','Digital Storytelling Studio','/learning-programs/catalogue-2/programs/digital-storytelling-studio.html','programme'),
('programme/disaster-risk-command','premium','Disaster Response Command Centre','/learning-programs/programs/disaster-risk-command.html','programme'),
('programme/earth-and-space-observatory','premium','Earth and Space Observatory','/learning-programs/catalogue-2/programs/earth-and-space-observatory.html','programme'),
('programme/ecosystem-ranger','premium','Ecosystem Ranger Adventure Academy','/learning-programs/programs/ecosystem-ranger.html','programme'),
('programme/energy-smart-home','premium','Energy-Smart Dream Home Challenge','/learning-programs/programs/energy-smart-home.html','programme'),
('programme/entrepreneurship-and-e-commerce-lab','premium','Entrepreneurship and E-Commerce Lab','/learning-programs/catalogue-2/programs/entrepreneurship-and-e-commerce-lab.html','programme'),
('programme/five-senses-lab','premium','Super Senses Discovery Lab','/learning-programs/programs/five-senses-lab.html','programme'),
('programme/food-science-investigation','premium','Food Science Investigation','/learning-programs/catalogue-2/programs/food-science-investigation.html','programme'),
('programme/fraction-food-truck','premium','Fraction Food Truck Frenzy','/learning-programs/programs/fraction-food-truck.html','programme'),
('programme/green-technology-startup','free','GreenTech Startup Challenge','/learning-programs/programs/green-technology-startup.html','programme'),
('programme/healthy-food-cafe','premium','Healthy Heroes Food CafÃ©','/learning-programs/programs/healthy-food-cafe.html','programme'),
('programme/human-body-diagnostic','premium','Human Body Medical Detective Lab','/learning-programs/programs/human-body-diagnostic.html','programme'),
('programme/integer-expedition','free','Integer Mountain Expedition','/learning-programs/programs/integer-expedition.html','programme'),
('programme/language-debate-arena','premium','Language Debate Arena','/learning-programs/catalogue-2/programs/language-debate-arena.html','programme'),
('programme/little-explorers-village','free','Little Explorers Adventure Village','/learning-programs/programs/little-explorers-village.html','programme'),
('programme/living-things-care-centre','premium','Living World Rescue Centre','/learning-programs/programs/living-things-care-centre.html','programme'),
('programme/local-economy-market-challenge','premium','Local Economy Market Challenge','/learning-programs/catalogue-2/programs/local-economy-market-challenge.html','programme'),
('programme/malaysia-heritage-quest','premium','Malaysia Heritage Time-Travel Quest','/learning-programs/programs/malaysia-heritage-quest.html','programme'),
('programme/mini-makers-workshop','premium','Mini Makers Workshop','/learning-programs/catalogue-2/programs/mini-makers-workshop.html','programme'),
('programme/number-town-post-office','free','Number Town Delivery Heroes','/learning-programs/programs/number-town-post-office.html','programme'),
('programme/pattern-and-coding-trail','premium','Pattern and Coding Trail','/learning-programs/catalogue-2/programs/pattern-and-coding-trail.html','programme'),
('programme/personal-finance-challenge','premium','Money Master: Personal Finance Quest','/learning-programs/programs/personal-finance-challenge.html','programme'),
('programme/phonics-rescue-station','premium','Phonics Rescue Station','/learning-programs/catalogue-2/programs/phonics-rescue-station.html','programme'),
('programme/plant-growth-research-station','premium','Plant Growth Research Station','/learning-programs/catalogue-2/programs/plant-growth-research-station.html','programme'),
('programme/renewable-island-operations','premium','Renewable Island Operations','/learning-programs/catalogue-2/programs/renewable-island-operations.html','programme'),
('programme/sabah-river-explorer','premium','Sabah River Explorer','/learning-programs/catalogue-2/programs/sabah-river-explorer.html','programme'),
('programme/safe-internet-junior','premium','Safe Internet Junior','/learning-programs/catalogue-2/programs/safe-internet-junior.html','programme'),
('programme/shape-and-motion-playground','premium','Shape and Motion Playground','/learning-programs/catalogue-2/programs/shape-and-motion-playground.html','programme'),
('programme/smart-city-network','premium','Smart City Network Command Centre','/learning-programs/programs/smart-city-network.html','programme'),
('programme/smart-transport-planner','premium','Smart Transport City Planner','/learning-programs/programs/smart-transport-planner.html','programme'),
('programme/statistical-investigation','premium','Statistical Detective Investigation Unit','/learning-programs/programs/statistical-investigation.html','programme'),
('programme/storybook-creator-studio','premium','Storybook Creator Studio','/learning-programs/catalogue-2/programs/storybook-creator-studio.html','programme'),
('programme/story-garden-adventure','premium','Story Garden Adventure','/learning-programs/catalogue-2/programs/story-garden-adventure.html','programme'),
('programme/sustainable-agriculture-simulator','premium','Sustainable Agriculture Simulator','/learning-programs/catalogue-2/programs/sustainable-agriculture-simulator.html','programme'),
('programme/sustainable-school-engineer','premium','Eco-School Engineering Challenge','/learning-programs/programs/sustainable-school-engineer.html','programme'),
('programme/water-cycle-rescue','premium','Water Cycle Rescue Squad','/learning-programs/programs/water-cycle-rescue.html','programme'),
('programme/weather-watch-junior','premium','Junior Weather Detective HQ','/learning-programs/programs/weather-watch-junior.html','programme'),
('programme/young-data-journalist','premium','Data Newsroom: Junior Journalist Mission','/learning-programs/programs/young-data-journalist.html','programme'),
('programme/young-inventor-design-lab','premium','Young Inventor Design Lab','/learning-programs/catalogue-2/programs/young-inventor-design-lab.html','programme'),
('quiz/form1','free','Form 1','/form1.html','quiz'),
('quiz/form2','free','Form 2','/form2.html','quiz'),
('quiz/form3','free','Form 3','/form3.html','quiz'),
('quiz/form4','free','Form 4','/form4.html','quiz'),
('quiz/form5','free','Form 5','/form5.html','quiz'),
('quiz/preschool','free','Preschool Mathematics Quiz','/preschool.html','quiz'),
('quiz/year1','free','Year 1 Mathematics Quiz','/year1.html','quiz'),
('quiz/year2','free','Year 2 Mathematics Quiz','/year2.html','quiz'),
('quiz/year3','free','Year 3 Mathematics Quiz','/year3.html','quiz'),
('quiz/year4','free','Year 4 Mathematics Quiz','/year4.html','quiz'),
('quiz/year5','free','Year 5 Mathematics Quiz','/year5.html','quiz'),
('quiz/year6','free','Year 6 Mathematics Quiz','/year6.html','quiz'),
('tool/addmath-solver','premium','Additional Mathematics Solver','/tools/addmath-solver/','tool'),
('tool/ai-homework-checker','premium','AI Homework Checker','/tools/ai-homework-checker/','tool'),
('tool/answer-scheme-generator','premium','Answer Scheme Generator','/tools/answer-scheme-generator/','tool'),
('tool/cj-ai-image-creator','premium','CJ AI Image Creator','/tools/cj-ai-image-creator/','tool'),
('tool/exam-paper-generator','premium','Exam Paper Generator','/tools/exam-paper-generator/','tool'),
('tool/flashcard-generator','premium','Math Flashcard Generator','/tools/flashcard-generator/','tool'),
('tool/math-quiz-generator','premium','Math Quiz Generator','/tools/math-quiz-generator/','tool'),
('tool/pdf-to-word','premium','CJ PDF to Word Converter','/tools/pdf-to-word/','tool'),
('tool/quiz-prompt-builder','premium','CJ Quiz Prompt Builder','/tools/quiz-prompt-builder/','tool'),
('tool/sabah-navigator-mvp','free','Sabah Navigator MVP','/tools/sabah-navigator-mvp/','tool'),
('tool/speed-test','free','MathToolsHub Speed Test','/tools/speed-test/','tool'),
('tool/step-by-step-math-solver','premium','Step-by-Step Math Solver','/tools/step-by-step-math-solver/','tool'),
('tool/student-notepad','free','Student Notepad','/tools/student-notepad/','tool'),
('tool/student-progress-tracker','premium','Student Progress Tracker','/tools/student-progress-tracker/','tool'),
('game/badminton-championship','premium','Badminton Championship','/games/badminton-championship/','game'),
('game/tennis-championship','premium','Tennis Championship','/games/tennis-championship/','game'),
('game/sniper-elite-hunter','premium','Sniper Elite Hunter','/games/sniper-elite-hunter/','game'),
('game/sniper-shadow-ops','premium','Sniper: Shadow Ops','/games/sniper-shadow-ops/','game'),
('tool/worksheet-generator','premium','Worksheet Generator','/tools/worksheet-generator/','tool')
on conflict (activity_id) do update set access_tier=excluded.access_tier,title=excluded.title,path=excluded.path,category=excluded.category,active=true,updated_at=now();
