-- MathToolsHub database-driven catalogue
-- Run in Supabase Dashboard > SQL Editor.
create table if not exists public.catalogue_items (
 id bigint generated by default as identity primary key,
 activity_id text unique not null check (char_length(activity_id) between 1 and 120),
 title text not null, description text not null default '', url text not null,
 section text not null check (section in ('primary','secondary')),
 icon text not null default '∑', sort_order integer not null default 0,
 active boolean not null default true, featured boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.catalogue_items enable row level security;
drop policy if exists "Anyone reads active catalogue" on public.catalogue_items;
create policy "Anyone reads active catalogue" on public.catalogue_items for select to anon,authenticated using(active=true);
drop policy if exists "Admins manage catalogue" on public.catalogue_items;
create policy "Admins manage catalogue" on public.catalogue_items for all to authenticated
 using(exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin'))
 with check(exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin'));
grant select on public.catalogue_items to anon,authenticated;
grant insert,update,delete on public.catalogue_items to authenticated;
grant usage,select on sequence public.catalogue_items_id_seq to authenticated;
insert into public.catalogue_items(activity_id,title,description,url,section,icon,sort_order) values
('quiz/preschool','Preschool Mathematics Quiz','100 interactive foundation mathematics questions','preschool.html','primary','★',10),
('game/preschool-cartoon','Preschool Interactive Cartoon','Counting, colours and animals in Happy Learning Forest','games/preschool_interactive_cartoon.html','primary','🌈',20),
('quiz/year1','Year 1 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year1.html','primary','+',30),
('game/escape-year1','Year 1 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape-room-mathematics-year1/','primary','🏝️',40),
('quiz/year2','Year 2 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year2.html','primary','−',50),
('game/escape-year2','Year 2 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape-room-mathematics-year2/','primary','🏝️',60),
('quiz/year3','Year 3 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year3.html','primary','×',70),
('game/escape-year3','Year 3 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape-room-mathematics-year3/','primary','🏝️',80),
('quiz/year4','Year 4 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year4.html','primary','÷',90),
('game/escape-year4','Year 4 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape-room-mathematics-year4/','primary','🏝️',100),
('quiz/year5','Year 5 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year5.html','primary','=',110),
('game/escape-year5','Year 5 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape-room-mathematics-year5/','primary','🏝️',120),
('quiz/year6','Year 6 Mathematics Quiz','100 interactive curriculum-based mathematics questions','year6.html','primary','π',130),
('game/escape-year6','Year 6 Mathematics Escape Room','Solve six island challenges and collect the keys','games/escape_room_mathematics_year6.html','primary','🏝️',140),
('quiz/form1','Form 1','Secondary programme','form1.html','secondary','x',10),
('game/form1-mission','Form 1 Math Detective Academy','Investigate cases using integers, ratios and algebra','games/secondary-math-missions/?form=1','secondary','🎯',20),
('quiz/form2','Form 2','Secondary programme','form2.html','secondary','x²',30),
('game/form2-mission','Form 2 Geometry Architect Challenge','Design structures using patterns, coordinates and geometry','games/secondary-math-missions/?form=2','secondary','🎯',40),
('quiz/form3','Form 3','Secondary programme','form3.html','secondary','√',50),
('game/form3-mission','Form 3 Math Business Simulator','Run a virtual business using finance and statistics','games/secondary-math-missions/?form=3','secondary','🎯',60),
('quiz/form4','Form 4','Secondary programme','form4.html','secondary','Σ',70),
('game/form4-mission','Form 4 Math City Rescue Mission','Restore a city using functions, graphs and probability','games/secondary-math-missions/?form=4','secondary','🎯',80),
('quiz/form5','Form 5','Secondary programme','form5.html','secondary','∞',90),
('game/form5-mission','Form 5 SPM Mathematics Challenge Arena','Complete six high-impact SPM mathematics challenges','games/secondary-math-missions/?form=5','secondary','🎯',100)
on conflict(activity_id) do update set title=excluded.title,description=excluded.description,url=excluded.url,section=excluded.section,icon=excluded.icon,sort_order=excluded.sort_order,updated_at=now();
