-- MathToolsHub initial Supabase schema
-- Run once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Student' check (char_length(display_name) between 1 and 50),
  education_level text check (education_level is null or education_level in ('preschool','year1','year2','year3','year4','year5','year6','form1','form2','form3','form4','form5','teacher')),
  role text not null default 'student' check (role in ('student','teacher','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id text not null check (char_length(activity_id) between 1 and 120),
  activity_type text not null default 'quiz' check (activity_type in ('quiz','game','course','tool')),
  score numeric not null default 0,
  progress jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, activity_id)
);

alter table public.profiles enable row level security;
alter table public.learning_progress enable row level security;

create policy "Users read own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "Users update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "Users read own progress" on public.learning_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own progress" on public.learning_progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users update own progress" on public.learning_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users delete own progress" on public.learning_progress for delete to authenticated using ((select auth.uid()) = user_id);

grant select on public.profiles to authenticated;
grant update (display_name, education_level, updated_at) on public.profiles to authenticated;
grant select, insert, update, delete on public.learning_progress to authenticated;

grant usage, select on sequence public.learning_progress_id_seq to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), 'Student'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();