const GAMES={
  integers:{title:"Integer Ice Climb",mission:"Climb by solving the integer challenge.",make:l=>{const m=l===0?10:l===1?30:80,a=ri(-m,m),b=ri(-m,m),op=pick(l<2?["+","−"]:["+","−","×"]),ans=op==="+"?a+b:op==="−"?a-b:a*b;return q(`${a} ${op} (${b})`,ans,op==="×"?"Multiply signs first.":"Track direction carefully on the number line.")}},
  fractions:{title:"Fraction Lab",mission:"Balance the fraction experiment.",make:l=>{let d=pick(l===0?[2,3,4,5]:[4,6,8,10,12]),a=ri(1,d-1),b=ri(1,d-1),ans=a+b;return q(`${a}/${d} + ${b}/${d}`,`${ans}/${d}`,"Keep the common denominator and add the numerators.",[`$${ans}/${d}$`])}},
  ratio:{title:"Ratio Racer",mission:"Tune the racer with equivalent ratios.",make:l=>{const a=ri(2,8),b=ri(2,9),k=ri(2,l+4),ans=b*k;return q(`${a}:${b} = ${a*k}:?`,ans,`Both ratio terms are multiplied by ${k}.`)}},
  percent:{title:"Percentage Market",mission:"Find the correct market value.",make:l=>{const p=pick(l===0?[10,20,25,50]:[5,10,15,20,25,30,40,50]),n=pick([20,40,60,80,100,120,160,200]),ans=p*n/100;return q(`${p}% of ${n}`,ans,`Calculate ${p}/100 × ${n}.`)}},
  algebra:{title:"Algebra Codebreaker",mission:"Crack the value of x.",make:l=>{const x=ri(l?2:1,l===2?15:10),a=ri(2,l===2?9:5),b=ri(1,12),total=a*x+b;return q(`${a}x + ${b} = ${total}`,x,`Subtract ${b}, then divide by ${a}.`)}},
  coordinates:{title:"Coordinate Quest",mission:"Navigate the coordinate grid.",make:l=>{const x=ri(-8,8),y=ri(-8,8),ask=pick(["quadrant","reflectX","reflectY"]);if(ask==="quadrant"){const ans=x===0||y===0?"On an axis":x>0&&y>0?"Quadrant I":x<0&&y>0?"Quadrant II":x<0?"Quadrant III":"Quadrant IV";return q(`Where is (${x}, ${y})?`,ans,"Check the signs of x and y.")}const ans=ask==="reflectX"?`(${x}, ${-y})`:`(${-x}, ${y})`;return q(`Reflect (${x}, ${y}) in the ${ask==="reflectX"?"x":"y"}-axis`,ans,`Change the sign of the ${ask==="reflectX"?"y":"x"}-coordinate.`)}},
  geometry:{title:"Geometry Architect",mission:"Complete the blueprint calculation.",make:l=>{const type=pick(l===0?["rectangle","triangle"]:["rectangle","triangle","circle"]),a=ri(3,14),b=ri(3,12);if(type==="rectangle")return q(`Area of ${a} × ${b} rectangle`,a*b,"Area = length × width.");if(type==="triangle")return q(`Area: base ${a*2}, height ${b}`,a*b,"Area = ½ × base × height.");return q(`Circumference, radius ${a} (use π≈3.14)`,fmt(2*3.14*a),"Circumference = 2πr.")}},
  statistics:{title:"Statistics Stadium",mission:"Analyse the team data.",make:l=>{const nums=Array.from({length:l+4},()=>ri(2,16));const ask=pick(["mean","median","range"]);let ans;if(ask==="mean"){const base=ri(3,12);for(let i=0;i<nums.length;i++)nums[i]=base+i;ans=nums.reduce((s,n)=>s+n,0)/nums.length}else if(ask==="median"){nums.sort((a,b)=>a-b);ans=nums.length%2?nums[(nums.length-1)/2]:(nums[nums.length/2-1]+nums[nums.length/2])/2}else ans=Math.max(...nums)-Math.min(...nums);return q(`${cap(ask)} of ${nums.join(", ")}`,fmt(ans),ask==="range"?"Maximum minus minimum.":ask==="median"?"Order values and find the middle.":"Sum values and divide by their number.")}},
  probability:{title:"Probability Carnival",mission:"Predict the carnival outcome.",make:l=>{const red=ri(1,6),blue=ri(1,6),total=red+blue,ask=pick(["red","blue"]),n=ask==="red"?red:blue,g=gcd(n,total);return q(`${red} red, ${blue} blue: P(${ask})`,`${n/g}/${total/g}`,"Favourable outcomes ÷ total outcomes.")}},
  sequences:{title:"Sequence Signal",mission:"Decode the next transmission.",make:l=>{const start=ri(1,12),step=ri(2,l===2?9:6),seq=Array.from({length:5},(_,i)=>start+i*step),ans=start+5*step;return q(`${seq.join(", ")}, ?`,ans,`The common difference is ${step}.`)}},
  pythagoras:{title:"Pythagoras Rescue",mission:"Find the missing side to complete the rescue.",make:l=>{const triples=pick([ [3,4,5],[5,12,13],[6,8,10],[8,15,17] ]),ask=l===0?2:ri(0,2),shown=triples.map((n,i)=>i===ask?"?":n);return q(`Right triangle sides: ${shown.join(", ")}`,triples[ask],ask===2?"Use c² = a² + b².":"Use a² = c² − b².")}},
  linear:{title:"Linear Graph Flight",mission:"Plot the correct flight path.",make:l=>{const m=ri(-4,5)||2,c=ri(-6,6),x=ri(-4,6),ans=m*x+c;return q(`y = ${m}x ${c<0?"−":"+"} ${Math.abs(c)}, when x = ${x}`,ans,"Substitute x, multiply, then add the intercept.")}},
  exponents:{title:"Exponent Power-Up",mission:"Power the reactor using index laws.",make:l=>{const a=ri(2,l===2?6:4),m=ri(1,l+3),n=ri(1,l+3),op=pick(["multiply","divide"]);if(op==="multiply")return q(`${a}^${m} × ${a}^${n} = ${a}^?`,m+n,"When multiplying equal bases, add the indices.");const high=m+n;return q(`${a}^${high} ÷ ${a}^${m} = ${a}^?`,n,"When dividing equal bases, subtract the indices.")}},
  factors:{title:"Factor Factory",mission:"Sort numbers using factors and multiples.",make:l=>{const type=pick(["gcf","lcm"]),a=ri(2,l===2?18:12),b=ri(2,l===2?18:12);return q(`${type==="gcf"?"HCF":"LCM"} of ${a} and ${b}`,type==="gcf"?gcd(a,b):a*b/gcd(a,b),type==="gcf"?"Find the greatest factor shared by both numbers.":"Find the smallest positive multiple shared by both numbers.")}},
  balance:{title:"Equation Balance Lab",mission:"Keep both sides of the equation balanced.",make:l=>{const x=ri(1,12),a=ri(2,l+5),b=ri(1,10),c=ri(1,8),total=a*x+b+c;return q(`${a}x + ${b} + ${c} = ${total}`,x,`Subtract ${b+c}, then divide by ${a}.`)}},
  angles:{title:"Angle Detective",mission:"Investigate the missing angle.",make:l=>{const type=pick(l===0?["line","right"]:["line","right","triangle"]),a=ri(15,75);if(type==="line")return q(`Angle on a straight line with ${a}°`,180-a,"Angles on a straight line total 180°.");if(type==="right")return q(`Angle completing 90° with ${a}°`,90-a,"Angles in a right angle total 90°.");const b=ri(20,80),aa=Math.min(a,140-b);return q(`Third triangle angle: ${aa}°, ${b}°, ?`,180-aa-b,"Angles in a triangle total 180°.")}},
  transforms:{title:"Transformation Portal",mission:"Transform coordinates to open the portal.",make:l=>{const x=ri(-6,6),y=ri(-6,6),dx=ri(-4,4),dy=ri(-4,4),kind=pick(l===0?["translate"]:["translate","rotate"]);return kind==="translate"?q(`Translate (${x}, ${y}) by (${dx}, ${dy})`,`(${x+dx}, ${y+dy})`,"Add the translation vector to the coordinates."):q(`Rotate (${x}, ${y}) 180° about origin`,`(${-x}, ${-y})`,"A 180° rotation changes both signs.")}},
  trig:{title:"Trigonometry Tower",mission:"Use trigonometric ratios to climb the tower.",make:l=>{const triples=pick([[3,4,5],[5,12,13],[8,15,17]]),ask=pick(["sin","cos","tan"]),[o,a,h]=triples,g=ask==="sin"?gcd(o,h):ask==="cos"?gcd(a,h):gcd(o,a),ans=ask==="sin"?`${o/g}/${h/g}`:ask==="cos"?`${a/g}/${h/g}`:`${o/g}/${a/g}`;return q(`${ask} θ (opposite ${o}, adjacent ${a}, hypotenuse ${h})`,ans,ask==="sin"?"sin = opposite/hypotenuse.":ask==="cos"?"cos = adjacent/hypotenuse.":"tan = opposite/adjacent.")}},
  finance:{title:"Financial Math Tycoon",mission:"Grow the business with accurate calculations.",make:l=>{const principal=pick([100,200,400,500,800,1000]),rate=pick([5,10,15]),years=ri(1,l+3),interest=principal*rate*years/100;return q(`Simple interest: RM${principal} at ${rate}% for ${years} year${years>1?"s":""}`,interest,`I = P × R × T = RM${interest}.`)}},
  speed:{title:"Speed Distance Rally",mission:"Calculate the rally route before time runs out.",make:l=>{const speed=pick([30,40,50,60,80,90]),time=ri(1,l+4),ask=pick(["distance","speed"]);return ask==="distance"?q(`${speed} km/h for ${time} h: distance?`,speed*time,"Distance = speed × time."):q(`${speed*time} km in ${time} h: speed?`,speed,"Speed = distance ÷ time.")}}
};
let game,level=0,round=0,score=0,lives=3,correct=0,answer,current;
const $=id=>document.getElementById(id),ri=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[Math.floor(Math.random()*a.length)],fmt=n=>Number.isInteger(n)?n:Number(n.toFixed(2)),cap=s=>s[0].toUpperCase()+s.slice(1),gcd=(a,b)=>b?gcd(b,a%b):a;
function q(text,ans,explain){return{text,ans:String(ans),explain}}
function init(){game=GAMES[document.body.dataset.game];$("title").textContent=game.title;$("mission").textContent=game.mission;document.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-level]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");level=+b.dataset.level});$("start").onclick=start;$("restart").onclick=start;$("again").onclick=start;$("levels").onclick=home}
function start(){round=score=correct=0;lives=3;$("startScreen").classList.add("hidden");$("endScreen").classList.add("hidden");$("playScreen").classList.remove("hidden");next()}
function next(){if(round>=10||lives<=0)return finish();round++;current=game.make(level);answer=current.ans;$("question").textContent=current.text;$("round").textContent=`Question ${round}/10`;$("score").textContent=score;$("lives").textContent=lives?"♥".repeat(lives):"0";$("bar").style.width=`${round*10}%`;$("feedback").textContent="";renderAnswers()}
function distract(ans){const n=Number(ans);if(!Number.isNaN(n))return String(fmt(n+pick([-3,-2,-1,1,2,3])));if(/^\(-?\d+, -?\d+\)$/.test(ans)){const ns=ans.match(/-?\d+/g).map(Number);return `(${ns[0]+pick([-2,-1,1,2])}, ${ns[1]+pick([-2,-1,1,2])})`}if(/^\d+\/\d+$/.test(ans)){const [a,b]=ans.split("/").map(Number);return `${Math.max(1,a+pick([-2,-1,1,2]))}/${b}`}const pools={"Quadrant I":["Quadrant II","Quadrant III","Quadrant IV","On an axis"],"Quadrant II":["Quadrant I","Quadrant III","Quadrant IV","On an axis"],"Quadrant III":["Quadrant I","Quadrant II","Quadrant IV","On an axis"],"Quadrant IV":["Quadrant I","Quadrant II","Quadrant III","On an axis"],"On an axis":["Quadrant I","Quadrant II","Quadrant III","Quadrant IV"]};return pick(pools[ans]||["0","1","Cannot tell"])}
function renderAnswers(){const vals=new Set([answer]);let guard=0;while(vals.size<4&&guard++<30)vals.add(distract(answer));const box=$("answers");box.innerHTML="";[...vals].sort(()=>Math.random()-.5).forEach(v=>{const b=document.createElement("button");b.className="answer";b.textContent=v;b.onclick=()=>check(v);box.appendChild(b)})}
function check(v){document.querySelectorAll(".answer").forEach(b=>b.disabled=true);const ok=v===answer;if(ok){score+=10+(level*5);correct++;$("feedback").textContent=`Correct! ${current.explain}`;$("feedback").className="feedback good"}else{lives--;$("feedback").textContent=`Answer: ${answer}. ${current.explain}`;$("feedback").className="feedback bad"}$("score").textContent=score;$("lives").textContent=lives?"♥".repeat(lives):"0";setTimeout(next,1200)}
function finish(){const pct=correct*10;$("playScreen").classList.add("hidden");$("endScreen").classList.remove("hidden");$("stars").textContent=pct>=80?"★★★":pct>=50?"★★":"★";$("result").textContent=`Score ${score} • ${correct}/10 correct`;$("message").textContent=pct>=80?"Outstanding mathematical thinking!":pct>=50?"Good progress—try another level.":"Keep practising—you are building skill."}
function home(){ $("playScreen").classList.add("hidden");$("endScreen").classList.add("hidden");$("startScreen").classList.remove("hidden") }
document.addEventListener("DOMContentLoaded",init);
