import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const config=window.MATHTOOLSHUB_SUPABASE,panel=document.getElementById("personalDashboard");
if(config?.url&&config?.publishableKey&&panel){
 const client=createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 const byId=id=>document.getElementById(id),nameNode=byId("dashboardName"),activityNode=byId("dashboardActivities"),scoreNode=byId("dashboardScore"),recentNode=byId("dashboardRecent"),continueLink=byId("dashboardContinue"),signInPanel=byId("dashboardSignIn"),content=byId("dashboardContent");
 const fallbackUrls={"quiz/preschool":"preschool.html","quiz/year1":"year1.html","quiz/year2":"year2.html","quiz/year3":"year3.html","quiz/year4":"year4.html","quiz/year5":"year5.html","quiz/year6":"year6.html","quiz/form1":"form1.html","quiz/form2":"form2.html","quiz/form3":"form3.html","quiz/form4":"form4.html","quiz/form5":"form5.html","game/mathcity-builder":"games/mathcity-builder/","game/math-kingdom-defender":"games/math-kingdom-defender/"};
 const label=id=>id.replace(/^(quiz|game|course|tool)\//,"").replace(/[-_]/g," ").replace(/\b\w/g,letter=>letter.toUpperCase());
 async function render(session){panel.hidden=false;if(!session?.user){signInPanel.hidden=false;content.hidden=true;return;}signInPanel.hidden=true;content.hidden=false;let displayName=session.user.user_metadata?.display_name||session.user.email?.split("@")[0]||"User";
 const [{data:profile},{data:progress,error},{data:catalogue}]=await Promise.all([client.from("profiles").select("display_name").eq("id",session.user.id).maybeSingle(),client.from("learning_progress").select("activity_id,activity_type,score,progress,updated_at").eq("user_id",session.user.id).order("updated_at",{ascending:false}).limit(20),client.from("catalogue_items").select("activity_id,title,url").eq("active",true)]);
 if(profile?.display_name)displayName=profile.display_name;nameNode.textContent=displayName;if(error){recentNode.innerHTML='<li class="dashboard-empty">Progress will appear here after the Supabase schema is updated.</li>';activityNode.textContent="0";scoreNode.textContent="—";return;}
 const items=progress||[],catalogueMap=new Map((catalogue||[]).map(item=>[item.activity_id,item]));activityNode.textContent=String(items.length);const scored=items.map(item=>Number(item.score)).filter(Number.isFinite);scoreNode.textContent=scored.length?`${Math.round(scored.reduce((a,b)=>a+b,0)/scored.length)}`:"—";
 recentNode.innerHTML=items.length?items.slice(0,3).map(item=>{const entry=catalogueMap.get(item.activity_id),url=entry?.url||fallbackUrls[item.activity_id]||"quizzes.html",title=entry?.title||label(item.activity_id),date=new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric"}).format(new Date(item.updated_at));return `<li><a href="${url}"><strong>${title}</strong><span>${Number(item.score)||0} points · ${date}</span></a></li>`;}).join(""):'<li class="dashboard-empty">Start a quiz or game to create your learning history.</li>';
 const latest=items[0],entry=latest?catalogueMap.get(latest.activity_id):null;continueLink.href=latest?(entry?.url||fallbackUrls[latest.activity_id]||"quizzes.html"):"quizzes.html";continueLink.textContent=latest?`Continue ${entry?.title||label(latest.activity_id)} →`:"Choose your first activity →";}
 const {data:{session}}=await client.auth.getSession();await render(session);client.auth.onAuthStateChange((_event,nextSession)=>render(nextSession));
}
