(() => {
  const openButton=document.getElementById("siteSearchOpen"); if(!openButton)return;
  const words={
    en:{button:"Search",title:"Search learning activities",placeholder:"Search games, quizzes, programmes and tools",help:"Tip: press / to search from anywhere.",ready:"Enter a topic or activity name.",loading:"Loading activities…",failed:"Search is temporarily unavailable.",none:"No activities found. Try a different word.",results:n=>`${n} ${n===1?"result":"results"} found`,close:"Close search",free:"Free",premium:"Premium",categories:{game:"Game",quiz:"Quiz",programme:"Learning programme",tool:"Tool"}},
    ms:{button:"Cari",title:"Cari aktiviti pembelajaran",placeholder:"Cari permainan, kuiz, program dan alat",help:"Petua: tekan / untuk mencari dari mana-mana halaman.",ready:"Masukkan topik atau nama aktiviti.",loading:"Aktiviti sedang dimuatkan…",failed:"Carian tidak tersedia buat sementara waktu.",none:"Tiada aktiviti ditemukan. Cuba perkataan lain.",results:n=>`${n} hasil carian ditemukan`,close:"Tutup carian",free:"Percuma",premium:"Premium",categories:{game:"Permainan",quiz:"Kuiz",programme:"Program pembelajaran",tool:"Alat"}},
    zh:{button:"搜索",title:"搜索学习活动",placeholder:"搜索游戏、测验、课程和工具",help:"提示：在任何位置按 / 即可搜索。",ready:"请输入主题或活动名称。",loading:"正在加载活动…",failed:"搜索暂时不可用。",none:"未找到活动，请尝试其他关键词。",results:n=>`找到 ${n} 个结果`,close:"关闭搜索",free:"免费",premium:"高级",categories:{game:"游戏",quiz:"测验",programme:"学习课程",tool:"工具"}}
  };
  const dialog=document.createElement("section");
  dialog.className="site-search-dialog"; dialog.id="siteSearchDialog"; dialog.setAttribute("role","dialog"); dialog.setAttribute("aria-modal","true"); dialog.setAttribute("aria-labelledby","siteSearchTitle"); dialog.hidden=true;
  dialog.innerHTML=`<div class="site-search-panel"><div class="site-search-header"><h2 class="site-search-title" id="siteSearchTitle"></h2><button class="site-search-close" type="button"><span aria-hidden="true">×</span></button></div><div class="site-search-field-wrap"><input class="site-search-field" id="siteSearchField" type="search" autocomplete="off"><p class="site-search-help" id="siteSearchHelp"></p></div><p class="site-search-status" id="siteSearchStatus" aria-live="polite"></p><ul class="site-search-results" id="siteSearchResults"></ul></div>`;
  document.body.append(dialog);
  const closeButton=dialog.querySelector(".site-search-close"),field=dialog.querySelector(".site-search-field"),title=dialog.querySelector(".site-search-title"),help=dialog.querySelector(".site-search-help"),status=dialog.querySelector(".site-search-status"),results=dialog.querySelector(".site-search-results"),languageSelect=document.getElementById("languageSelect");
  let activities=[],loadPromise,lastFocus;
  const currentLanguage=()=>words[languageSelect?.value]?languageSelect.value:"en", text=()=>words[currentLanguage()], normalise=value=>String(value||"").toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
  function translateInterface(){const copy=text();openButton.querySelector(".site-search-label").textContent=copy.button;title.textContent=copy.title;field.placeholder=copy.placeholder;field.setAttribute("aria-label",copy.placeholder);help.textContent=copy.help;closeButton.setAttribute("aria-label",copy.close);search();}
  function loadActivities(){if(!loadPromise){status.textContent=text().loading;loadPromise=fetch("activity-entitlements.json",{headers:{Accept:"application/json"}}).then(response=>{if(!response.ok)throw new Error("Activity catalogue unavailable");return response.json();}).then(data=>{activities=Array.isArray(data.activities)?data.activities:[];}).catch(()=>{status.textContent=text().failed;});}return loadPromise;}
  function search(){const copy=text(),query=normalise(field.value.trim());results.replaceChildren();if(!query){status.textContent=copy.ready;return;}const matches=activities.filter(activity=>normalise(`${activity.title} ${activity.category} ${activity.activity_id}`).includes(query)).slice(0,24);status.textContent=matches.length?copy.results(matches.length):copy.none;const fragment=document.createDocumentFragment();matches.forEach(activity=>{const item=document.createElement("li"),link=document.createElement("a"),activityTitle=document.createElement("span"),meta=document.createElement("span"),tier=document.createElement("span");link.className="site-search-result-link";link.href=activity.path;activityTitle.className="site-search-result-title";activityTitle.textContent=activity.title;meta.className="site-search-result-meta";meta.textContent=copy.categories[activity.category]||activity.category;tier.className=`site-search-tier is-${activity.access_tier}`;tier.textContent=activity.access_tier==="free"?copy.free:copy.premium;link.append(activityTitle,meta,tier);item.append(link);fragment.append(item);});results.append(fragment);}
  async function openSearch(){lastFocus=document.activeElement;dialog.hidden=false;document.body.classList.add("site-search-locked");await loadActivities();search();field.focus();}
  function closeSearch(){dialog.hidden=true;document.body.classList.remove("site-search-locked");lastFocus?.focus();}
  openButton.addEventListener("click",openSearch);closeButton.addEventListener("click",closeSearch);dialog.addEventListener("pointerdown",event=>{if(event.target===dialog)closeSearch();});field.addEventListener("input",search);languageSelect?.addEventListener("change",translateInterface);
  document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!dialog.hidden)closeSearch();if(event.key==="/"&&dialog.hidden&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)){event.preventDefault();openSearch();}});
  translateInterface();const initialQuery=new URLSearchParams(location.search).get("search");if(initialQuery){field.value=initialQuery;openSearch();}
})();