
let level="easy",round=0,score=0,lives=3,correct=0,answer=null,locked=false,sound=true;
const $=id=>document.getElementById(id);
document.querySelectorAll(".level").forEach(b=>b.onclick=()=>{document.querySelectorAll(".level").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");level=b.dataset.level;$("levelLabel").textContent=GAME.levels[level].label});
$("startBtn").onclick=start;$("restartBtn").onclick=start;$("againBtn").onclick=start;$("homeBtn").onclick=()=>{$("play").classList.add("hidden");$("end").classList.add("hidden");$("start").classList.remove("hidden")};
$("soundBtn").onclick=()=>{sound=!sound;$("soundBtn").textContent=sound?"🔊 Sound On":"🔇 Sound Off"};
function start(){round=0;score=0;lives=3;correct=0;locked=false;$("start").classList.add("hidden");$("end").classList.add("hidden");$("play").classList.remove("hidden");update();next()}
function next(){let cfg=GAME.levels[level];if(round>=cfg.rounds||lives<=0){finish();return}round++;locked=false;$("feedback").textContent="";$("feedback").className="feedback";let r=GAME.build(level);answer=r.answer;$("question").textContent=r.question;$("tip").textContent=r.tip||GAME.tip;render(r.choices);$("roundLabel").textContent=`Round ${round} / ${cfg.rounds}`;$("progress").style.width=`${round/cfg.rounds*100}%`}
function render(c){$("answers").innerHTML="";shuffle([...new Set(c.map(String))]).forEach(v=>{let b=document.createElement("button");b.className="answer";b.textContent=v;b.onclick=()=>check(v);$("answers").appendChild(b)})}
function check(v){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>b.disabled=true);let ok=GAME.check?GAME.check(v,answer):String(v)===String(answer);if(ok){score+=level==="hard"?15:10;correct++;$("feedback").textContent=random(GAME.success);$("feedback").classList.add("correct");if(GAME.onCorrect)GAME.onCorrect();tone(660,.12)}else{lives--;$("feedback").textContent=`Good try! Correct answer: ${answer}`;$("feedback").classList.add("wrong");tone(180,.2)}update();setTimeout(next,1100)}
function update(){$("score").textContent=score;$("lives").textContent=lives>0?"❤️".repeat(lives):"💔";$("levelLabel").textContent=GAME.levels[level].label}
function finish(){$("play").classList.add("hidden");$("end").classList.remove("hidden");let acc=Math.round(correct/Math.max(1,GAME.levels[level].rounds)*100);$("stars").textContent=acc>=80?"⭐⭐⭐":acc>=50?"⭐⭐":"⭐";$("final").textContent=acc>=80?GAME.end[0]:acc>=50?GAME.end[1]:GAME.end[2];$("certScore").textContent=`Score: ${score} • Accuracy: ${acc}%`}
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}function random(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function tone(f,d){if(!sound)return;let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.1,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}
