(()=>{"use strict";
const id=window.PROGRAM_ID,cfg=window.PROGRAMS[id];if(!cfg){document.body.innerHTML="<p>Programme configuration not found.</p>";return}document.documentElement.style.setProperty("--accent",cfg.accent);
const key=`learning_quest_${id}`,state=read(key,{lessons:[],missions:{},quizScore:null,project:"",reflection:"",certificateName:""}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
$("#programIcon").textContent=cfg.icon;$("#programNo").textContent=`Programme ${cfg.no}`;$("#programLevel").textContent=cfg.level;$("#programTitle").textContent=cfg.title;$("#programIntro").textContent=cfg.intro;$("#programFocus").textContent=cfg.focus;$("#programSubjects").textContent=cfg.subjects.join(" · ");$("#projectProduct").textContent=cfg.product;$("#projectProductRepeat").textContent=cfg.product;$("#assessmentApproach").textContent=cfg.assessment;document.title=`${cfg.title} | MathToolsHub`;
$("#objectives").innerHTML=cfg.objectives.map(x=>`<div class="objective"><span class="check">✓</span><span>${esc(x)}</span></div>`).join("");
$("#learnCards").innerHTML=cfg.lessons.map((l,i)=>`<article class="card"><h3>${i+1}. ${esc(l.title)}</h3><p>${esc(l.body)}</p><div class="example"><strong>Try it:</strong> ${esc(l.example)}</div><div class="lesson-actions"><span class="lesson-done" id="lessonStatus${i}"></span><button class="primary lesson-btn" data-i="${i}" type="button">Mark as learned</button></div></article>`).join("");
$("#missionList").innerHTML=cfg.missions.map((m,i)=>`<article class="card mission-card"><h3>Activity ${i+1}: ${esc(cfg.lessons[i].title)}</h3><p>${esc(m.question)}</p><div class="options">${m.options.map((o,j)=>`<button class="option mission-option" data-mi="${i}" data-oi="${j}" type="button">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join("")}</div><div class="feedback" id="missionFeedback${i}"></div></article>`).join("");
$("#quizForm").innerHTML=cfg.quiz.map((q,i)=>`<fieldset class="quiz-item"><legend>${i+1}. ${esc(q.q)}</legend>${q.options.map((o,j)=>`<label class="choice"><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join("")}</fieldset>`).join("");
$("#projectWork").value=state.project;$("#reflection").value=state.reflection;$("#certificateName").value=state.certificateName;
$$('.nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.section,b)));$$('.lesson-btn').forEach(b=>b.addEventListener('click',()=>lesson(+b.dataset.i)));$$('.mission-option').forEach(b=>b.addEventListener('click',()=>mission(+b.dataset.mi,+b.dataset.oi)));$("#submitQuiz").addEventListener('click',quiz);$("#projectWork").addEventListener('input',e=>{state.project=e.target.value;save();progress()});$("#reflection").addEventListener('input',e=>{state.reflection=e.target.value;save();progress()});$("#certificateName").addEventListener('input',e=>{state.certificateName=e.target.value;save()});$("#downloadPortfolio").addEventListener('click',download);$("#printCertificate").addEventListener('click',printCertificate);$("#resetProgram").addEventListener('click',reset);
restore();progress();
function show(id,b){$$('.section').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x===b));scrollTo({top:0,behavior:'smooth'})}
function lesson(i){if(!state.lessons.includes(i))state.lessons.push(i);save();restore();progress()}
function mission(mi,oi){if(state.missions[mi]!==undefined)return;const m=cfg.missions[mi];state.missions[mi]=oi;paintMission(mi,oi);save();progress()}
function paintMission(mi,oi){const m=cfg.missions[mi];$$(`[data-mi="${mi}"]`).forEach((b,j)=>{b.disabled=true;if(j===m.answer)b.classList.add('correct');else if(j===oi)b.classList.add('wrong')});$(`#missionFeedback${mi}`).textContent=(oi===m.answer?'Correct. ':'Review this outcome. ')+m.feedback}
function quiz(){let score=0,answered=0;cfg.quiz.forEach((q,i)=>{const s=$(`input[name="q${i}"]:checked`);if(s){answered++;if(+s.value===q.answer)score++}});if(answered<cfg.quiz.length){alert('Please answer all assessment questions.');return}state.quizScore=score;save();showResult();progress()}
function showResult(){const pct=Math.round(state.quizScore/cfg.quiz.length*100);$("#scoreValue").textContent=`${state.quizScore}/${cfg.quiz.length}`;$("#scorePercent").textContent=`${pct}%`;$("#resultBadge").textContent=pct>=80?'Mastery Badge':pct>=60?'Progress Badge':'Keep Practising';$("#quizResult").style.display='block'}
function restore(){state.lessons.forEach(i=>{const s=$(`#lessonStatus${i}`),b=$(`.lesson-btn[data-i="${i}"]`);if(s)s.textContent='Completed ✓';if(b){b.disabled=true;b.textContent='Completed'}});Object.entries(state.missions).forEach(([mi,oi])=>paintMission(+mi,+oi));if(state.quizScore!==null)showResult()}
function progress(){const parts=9,done=state.lessons.length+Object.keys(state.missions).length+(state.quizScore!==null?1:0)+(state.project.trim()?1:0)+(state.reflection.trim()?1:0),pct=Math.round(done/parts*100);$("#progressBar").style.width=`${pct}%`;$("#progressText").textContent=`${pct}% complete`;$("#progressDetail").textContent=`${done} of ${parts} tasks completed`;$("#topStatus").textContent=pct===100?'Programme completed':`${pct}% progress`;const eligible=state.quizScore!==null&&state.quizScore/cfg.quiz.length>=.6;$("#certificateStatus").textContent=eligible?'Certificate unlocked':'Score at least 60% to unlock certificate';$("#printCertificate").disabled=!eligible;$("#certificateProgramme").textContent=cfg.title;$("#certificateLevel").textContent=cfg.level;$("#certificateDate").textContent=new Date().toLocaleDateString()}
function download(){const text=`${cfg.title}\n${'='.repeat(cfg.title.length)}\n\nStudent product: ${cfg.product}\n\nPROJECT WORK\n${state.project}\n\nREFLECTION\n${state.reflection}`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${id}-portfolio.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function printCertificate(){const name=$("#certificateName").value.trim();if(!name){alert("Enter the learner's name first.");return}state.certificateName=name;save();$("#certificateLearner").textContent=name;$("#certificate").classList.add('show');print()}
function reset(){if(confirm('Reset all progress for this programme?')){localStorage.removeItem(key);location.reload()}}
function save(){localStorage.setItem(key,JSON.stringify(state))}function read(k,f){try{return{...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}}
})();