function g(id){return document.getElementById(id)}
var current={objective:[],structured:[]};
var syllabus={
"Year 1":[["whole","Whole numbers to 100"],["addsub","Addition and subtraction"],["money","Money"],["time","Time"],["measure","Measurement"],["shapes","Shapes and space"],["data","Data handling"]],
"Year 2":[["whole","Whole numbers to 1,000"],["addsub","Addition and subtraction"],["multdiv","Multiplication and division"],["fractions","Fractions"],["money","Money"],["time","Time"],["measure","Measurement"],["shapes","Shapes and space"],["data","Data handling"]],
"Year 3":[["whole","Whole numbers to 10,000"],["operations","Basic operations"],["fractions","Fractions"],["decimals","Decimals"],["percentages","Percentages"],["money","Money"],["time","Time"],["measure","Measurement"],["shapes","Space"],["coordinates","Coordinates"],["data","Data handling"]],
"Year 4":[["whole","Whole numbers and operations"],["fractions","Fractions"],["decimals","Decimals"],["percentages","Percentages"],["money","Money"],["time","Time"],["measure","Measurement"],["geometry","Geometry"],["coordinates","Coordinates"],["ratio","Ratio and proportion"],["data","Data handling"]],
"Year 5":[["whole","Whole numbers and operations"],["fractions","Fractions"],["decimals","Decimals"],["percentages","Percentages"],["money","Money"],["time","Time"],["measure","Measurement"],["geometry","Geometry"],["coordinates","Coordinates"],["ratio","Ratio and proportion"],["data","Data handling and average"]],
"Year 6":[["whole","Whole numbers and operations"],["fractions","Fractions"],["decimals","Decimals"],["percentages","Percentages"],["money","Financial mathematics"],["time","Time"],["measure","Measurement"],["geometry","Geometry"],["coordinates","Coordinates"],["ratio","Ratio and proportion"],["speed","Speed"],["data","Data handling and probability"]],
"Form 1":[["integers","Integers"],["factors","Factors and multiples"],["powers","Squares, square roots, cubes and cube roots"],["ratio","Ratio, rate and proportion"],["algebra","Algebraic expressions"],["equations","Linear equations"],["inequalities","Linear inequalities"],["angles","Lines and angles"],["polygons","Basic polygons"],["area","Perimeter and area"],["sets","Sets"],["data","Data handling"],["pythagoras","Pythagoras' theorem"]],
"Form 2":[["patterns","Patterns and sequences"],["factorisation","Algebraic expansion and factorisation"],["formulae","Algebraic formulae"],["polygons","Polygons"],["circles","Circles"],["solids","Three-dimensional shapes"],["coordinates","Coordinates"],["graphs","Graphs of functions"],["speed","Speed and acceleration"],["gradient","Gradient"],["transformations","Isometric transformations"],["probability","Probability"]],
"Form 3":[["indices","Indices"],["standardform","Standard form"],["consumer","Consumer mathematics"],["scale","Scale drawings"],["trigonometry","Trigonometric ratios"],["angles","Angles and tangents of circles"],["plans","Plans and elevations"],["loci","Loci"],["straightlines","Straight lines"]],
"Form 4":[["quadratic","Quadratic functions and equations"],["bases","Number bases"],["logic","Logical reasoning"],["sets","Set operations"],["networks","Graphs and networks"],["inequalities","Linear inequalities in two variables"],["motion","Motion graphs"],["dispersion","Measures of dispersion"],["probability","Combined events"],["finance","Financial planning"]],
"Form 5":[["variation","Variation"],["matrices","Matrices"],["insurance","Consumer mathematics: insurance"],["taxation","Consumer mathematics: taxation"],["transformations","Transformations"],["congruency","Congruency and enlargement"],["triggraphs","Graphs of trigonometric functions"],["dispersion","Dispersion for grouped data"],["modeling","Mathematical modelling"]]
};
function rnd(max,min){min=min||0;return Math.floor(Math.random()*(max-min+1))+min}
function pick(items){return items[rnd(items.length-1)]}
function shuffle(items){for(var i=items.length-1;i>0;i--){var j=rnd(i),x=items[i];items[i]=items[j];items[j]=x}return items}
function esc(value){var d=document.createElement("div");d.textContent=value;return d.innerHTML}
function selectedGrade(){return g("yearForm").value}
function updateTopics(){var level=g("level").value,count=level==="primary"?6:5,label=level==="primary"?"Year":"Form",previous=g("yearForm").value,options=[];for(var i=1;i<=count;i++)options.push('<option value="'+label+" "+i+'">'+label+" "+i+"</option>");g("yearForm").innerHTML=options.join("");if(options.length&&previous.indexOf(label)===0)g("yearForm").value=previous;updateSyllabusTopics()}
function updateSyllabusTopics(){var grade=selectedGrade(),items=syllabus[grade]||[];g("topic").innerHTML='<option value="mixed">Mixed '+grade+' mathematics</option>'+items.map(function(item){return'<option value="'+item[0]+'">'+item[1]+"</option>"}).join("")}
function limits(grade){return{"Year 1":100,"Year 2":1000,"Year 3":10000,"Year 4":100000,"Year 5":1000000,"Year 6":10000000}[grade]||100}
function numeric(q,a,e){return{q:q,a:String(a),e:e}}
function primaryQuestion(topic,difficulty,grade){var year=Number(grade.split(" ")[1]),max=limits(grade),a,b,c,answer;
if(topic==="whole"){a=rnd(max);b=rnd(max-a);return numeric("Write the value of "+a+" + "+b+".",a+b,"Add the two whole numbers: "+a+" + "+b+" = "+(a+b)+".")}
if(topic==="addsub"||topic==="operations"){a=rnd(max);b=rnd(max);var op=topic==="addsub"?pick(["+","−"]):pick(["+","−","×","÷"]);if(op==="−"&&b>a){c=a;a=b;b=c}if(op==="×"){a=rnd(year+7,2);b=rnd(12,2)}if(op==="÷"){b=rnd(10,2);answer=rnd(year*3+5,2);a=b*answer}answer=op==="+"?a+b:op==="−"?a-b:op==="×"?a*b:a/b;return numeric("Calculate "+a+" "+op+" "+b+".",answer,a+" "+op+" "+b+" = "+answer+".")}
if(topic==="multdiv"){b=rnd(9,2);answer=rnd(10,2);a=b*answer;return difficulty==="easy"?numeric("Calculate "+b+" × "+answer+".",a,b+" groups of "+answer+" = "+a+"."):numeric("Calculate "+a+" ÷ "+b+".",answer,a+" ÷ "+b+" = "+answer+".")}
if(topic==="fractions"){var den=pick(year<4?[2,3,4,5,8]:[2,3,4,5,6,8,10,12]),n1=rnd(den-1,1),n2=rnd(den-1,1);return{q:"Calculate "+n1+"/"+den+" + "+n2+"/"+den+".",a:(n1+n2)+"/"+den,e:"The denominators are equal, so add the numerators: "+(n1+n2)+"/"+den+"."}}
if(topic==="decimals"){a=rnd(900,10)/10;b=rnd(90,1)/10;answer=Math.round((a+b)*10)/10;return numeric("Calculate "+a.toFixed(1)+" + "+b.toFixed(1)+".",answer,"Align the decimal points and add to get "+answer+".")}
if(topic==="percentages"){var rate=pick([10,20,25,50,75]),base=rnd(20,2)*20;answer=rate*base/100;return numeric("Find "+rate+"% of "+base+".",answer,rate+" ÷ 100 × "+base+" = "+answer+".")}
if(topic==="money"){a=rnd(10000,100)/100;b=rnd(Math.floor(a*100),1)/100;answer=Math.round((a-b)*100)/100;return numeric("A pupil has RM"+a.toFixed(2)+" and spends RM"+b.toFixed(2)+". How much remains?",answer.toFixed(2),"RM"+a.toFixed(2)+" − RM"+b.toFixed(2)+" = RM"+answer.toFixed(2)+".")}
if(topic==="time"){a=rnd(10,1);b=rnd(5,1);answer=a*60+b*15;return numeric("How many minutes are there in "+a+" hours and "+(b*15)+" minutes?",answer,"Multiply hours by 60, then add the remaining minutes.")}
if(topic==="measure"){a=rnd(20,2);b=rnd(20,2);answer=a*b;return numeric("A rectangle is "+a+" cm long and "+b+" cm wide. Find its area in cm².",answer,"Area = length × width = "+a+" × "+b+" = "+answer+" cm².")}
if(topic==="shapes"||topic==="geometry"){a=rnd(80,20);answer=180-a;return numeric("Two angles on a straight line are "+a+"° and x°. Find x.",answer,"Angles on a straight line total 180°, so x = 180° − "+a+"° = "+answer+"°.")}
if(topic==="coordinates"){a=rnd(8);b=rnd(8);return{q:"State the coordinates of a point "+a+" units right and "+b+" units up from the origin.",a:"("+a+", "+b+")",e:"Horizontal position is written first, followed by vertical position."}}
if(topic==="ratio"){a=rnd(8,2);b=rnd(8,2);c=rnd(5,2);return{q:"Simplify the ratio "+(a*c)+":"+(b*c)+".",a:a+":"+b,e:"Divide both terms by the common factor "+c+"."}}
if(topic==="speed"){a=rnd(80,20);b=rnd(5,2);return numeric("A vehicle travels "+(a*b)+" km in "+b+" hours. Find its speed in km/h.",a,"Speed = distance ÷ time = "+(a*b)+" ÷ "+b+" = "+a+" km/h.")}
a=rnd(20,4);b=rnd(20,4);c=rnd(20,4);answer=Math.round((a+b+c)/3*100)/100;return numeric("Find the mean of "+a+", "+b+" and "+c+".",answer,"Mean = sum ÷ number of values = "+answer+".")}
function secondaryQuestion(topic,difficulty,grade){var a=rnd(12,2),b=rnd(12,2),c,answer;
if(topic==="integers")return numeric("Calculate (−"+a+") + "+b+".",b-a,"Adding "+b+" to −"+a+" gives "+(b-a)+".");
if(topic==="factors"){answer=a*b;return numeric("Find the highest common factor of "+answer+" and "+(a*(b+1))+".",a,"Factor both numbers; their highest common factor is "+a+".")}
if(topic==="powers"||topic==="indices"){return numeric("Evaluate "+a+"².",a*a,a+"² = "+a+" × "+a+" = "+(a*a)+".")}
if(topic==="ratio"){c=rnd(5,2);return{q:"Simplify "+(a*c)+":"+(b*c)+".",a:a+":"+b,e:"Divide both terms by "+c+"."}}
if(topic==="algebra"){return{q:"Simplify "+a+"x + "+b+"x.",a:(a+b)+"x",e:"Combine like terms: ("+a+" + "+b+")x = "+(a+b)+"x."}}
if(topic==="equations"){answer=rnd(15,2);c=a*answer+b;return{q:"Solve "+a+"x + "+b+" = "+c+".",a:"x = "+answer,e:"Subtract "+b+" and divide by "+a+"."}}
if(topic==="inequalities"){answer=rnd(10,2);c=a*answer+b;return{q:"Solve "+a+"x + "+b+" < "+c+".",a:"x < "+answer,e:"Subtract "+b+" and divide by positive "+a+"."}}
if(topic==="angles"||topic==="polygons"){a=rnd(120,30);return numeric("An angle on a straight line is "+a+"°. Find the adjacent angle.",180-a,"Angles on a straight line sum to 180°.")}
if(topic==="area"){return numeric("Find the area of a triangle with base "+a+" cm and height "+b+" cm.",a*b/2,"Area = ½ × base × height.")}
if(topic==="sets"){return numeric("If n(A) = "+a+", n(B) = "+b+" and n(A ∩ B) = 2, find n(A ∪ B).",a+b-2,"Use n(A ∪ B) = n(A) + n(B) − n(A ∩ B).")}
if(topic==="pythagoras"){a=pick([3,6,9]);b=a/3*4;answer=a/3*5;return numeric("A right-angled triangle has shorter sides "+a+" cm and "+b+" cm. Find the hypotenuse.",answer,"Use c² = a² + b².")}
if(topic==="patterns"){return numeric("Find the next term: "+a+", "+(a+b)+", "+(a+2*b)+", ...",a+3*b,"The common difference is "+b+".")}
if(topic==="factorisation"){return{q:"Factorise "+a+"x + "+(a*b)+".",a:a+"(x + "+b+")",e:"Take out the common factor "+a+"."}}
if(topic==="formulae"){return numeric("Given y = "+a+"x + "+b+", find y when x = 3.",a*3+b,"Substitute x = 3.")}
if(topic==="circles"){return numeric("Find the circumference of a circle of radius 7 cm. Use π = 22/7.",44,"Circumference = 2πr = 44 cm.")}
if(topic==="solids"){return numeric("Find the volume of a cuboid measuring "+a+" cm × "+b+" cm × 5 cm.",a*b*5,"Volume = length × width × height.")}
if(topic==="coordinates"||topic==="gradient"||topic==="straightlines"){return numeric("Find the gradient through (0, 0) and ("+a+", "+(a*b)+").",b,"Gradient = change in y ÷ change in x.")}
if(topic==="graphs"){return numeric("For y = "+a+"x + "+b+", find y when x = 2.",2*a+b,"Substitute x = 2.")}
if(topic==="speed"||topic==="motion"){return numeric("A car travels "+(a*b)+" km in "+b+" hours. Find its average speed.",a,"Speed = distance ÷ time.")}
if(topic==="transformations"){return{q:"Translate ("+a+", "+b+") by vector (2, −3).",a:"("+(a+2)+", "+(b-3)+")",e:"Add 2 to x and subtract 3 from y."}}
if(topic==="probability"){return{q:"A bag contains "+a+" red and "+b+" blue counters. Find P(red).",a:a+"/"+(a+b),e:"Probability = favourable outcomes ÷ total outcomes."}}
if(topic==="standardform"){answer=a*100000;return{q:"Write "+answer+" in standard form.",a:a+" × 10⁵",e:"Move the decimal point five places left."}}
if(topic==="consumer"||topic==="finance"||topic==="insurance"||topic==="taxation"){var rate=pick([5,10,15]);answer=a*100*(1+rate/100);return numeric("RM"+(a*100)+" increases by "+rate+"%. Find the new amount.",answer.toFixed(2),"Multiply by "+(1+rate/100)+".")}
if(topic==="scale"){return numeric("On a 1:"+(a*100)+" drawing, a length is "+b+" cm. Find the actual length in cm.",a*100*b,"Multiply the drawing length by the scale factor.")}
if(topic==="trigonometry"){return numeric("In a right triangle, opposite = 3 and adjacent = 4. Find tan θ.",0.75,"tan θ = opposite ÷ adjacent = 3/4.")}
if(topic==="plans"){return{q:"Which view shows an object as seen directly from above?",a:"Plan",e:"A plan is the top view."}}
if(topic==="loci"){return{q:"Describe the locus of points 5 cm from a fixed point P.",a:"A circle with centre P and radius 5 cm",e:"All points at a constant distance from one point form a circle."}}
if(topic==="quadratic"){return{q:"Solve x² − "+(a+b)+"x + "+(a*b)+" = 0.",a:"x = "+a+" or x = "+b,e:"Factorise as (x − "+a+")(x − "+b+") = 0."}}
if(topic==="bases"){return numeric("Convert 1011₂ to base ten.",11,"8 + 0 + 2 + 1 = 11.")}
if(topic==="logic"){return{q:"State the negation of: All integers are positive.",a:"Not all integers are positive",e:"Negate the universal statement."}}
if(topic==="networks"){return numeric("A network has edge weights 4, 7 and 6 along a route. Find its total weight.",17,"Add the edge weights: 4 + 7 + 6.")}
if(topic==="dispersion"){return numeric("Find the range of 4, "+a+", 18 and 9.",18-Math.min(4,a),"Range = maximum − minimum.")}
if(topic==="variation"){return numeric("y varies directly as x. If y = "+(a*2)+" when x = 2, find y when x = 5.",a*5,"First find k = y/x = "+a+", then y = kx.")}
if(topic==="matrices"){return{q:"Add matrices [["+a+", 2], [3, 4]] and [[1, 5], [2, 1]].",a:"[["+(a+1)+", 7], [5, 5]]",e:"Add corresponding entries."}}
if(topic==="congruency"){return numeric("A shape is enlarged by scale factor 3 from an area of "+a+" cm². Find the new area.",a*9,"Area scale factor = 3² = 9.")}
if(topic==="triggraphs"){return numeric("State the amplitude of y = 4 sin x.",4,"Amplitude is the absolute value of the coefficient of sin x.")}
if(topic==="modeling"){return{q:"A taxi fare is RM4 plus RM2 per kilometre. Write a model for C after x kilometres.",a:"C = 4 + 2x",e:"Fixed charge + rate × distance."}}
return numeric("Calculate "+a+" + "+b+".",a+b,"Add the values.")}
function create(grade,topic,difficulty){var choices=syllabus[grade]||[];if(topic==="mixed")topic=pick(choices)[0];return grade.indexOf("Year")===0?primaryQuestion(topic,difficulty,grade):secondaryQuestion(topic,difficulty,grade)}
function choices(answer){var correct=String(answer),items=[correct],n;if(/^-?\d+(\.\d+)?$/.test(correct)){n=Number(correct);[1,-1,2].forEach(function(d){items.push(String(Math.round((n+d*(Math.abs(n)>50?5:1))*100)/100))})}else if(/^x\s*[=<]/.test(correct)){items.push(correct.replace(/-?\d+(\.\d+)?/,function(v){return Number(v)+1}),correct.replace(/-?\d+(\.\d+)?/,function(v){return Number(v)-1}),"No solution")}else{items.push("None of these","Cannot be determined","0")}return shuffle(Array.from(new Set(items))).slice(0,4)}
function generate(){var grade=selectedGrade(),topic=g("topic").value,difficulty=g("difficulty").value,o=Number(g("objective").value),s=Number(g("structured").value),writtenMarks=Number(g("marks").value);current={objective:[],structured:[]};for(var i=0;i<o;i++){var item=create(grade,topic,difficulty);item.options=choices(item.a);current.objective.push(item)}for(var j=0;j<s;j++)current.structured.push(create(grade,topic,difficulty));var total=o+s*writtenMarks;var objective=current.objective.map(function(item,i){return'<li>'+esc(item.q)+'<div class="choices">'+item.options.map(function(option,k){return"<span>"+String.fromCharCode(65+k)+". "+esc(option)+"</span>"}).join("")+"</div></li>"}).join("");var structured=current.structured.map(function(item){var lines="";for(var k=0;k<Math.max(2,writtenMarks);k++)lines+="<span></span>";return'<li>'+esc(item.q)+' <span class="marks">['+writtenMarks+" marks]</span><div class='work-lines'>"+lines+"</div></li>"}).join("");var scheme="";if(g("scheme").checked){var rows=current.objective.map(function(item,i){return"<tr><td>A"+(i+1)+"</td><td>"+esc(item.a)+"</td><td>1</td></tr>"}).join("")+current.structured.map(function(item,i){return"<tr><td>B"+(i+1)+"</td><td>"+esc(item.a)+" — "+esc(item.e)+"</td><td>"+writtenMarks+"</td></tr>"}).join("");scheme='<section class="scheme '+(g("newPage").checked?"new-page":"")+'"><h2>Marking Scheme</h2><table><thead><tr><th>Question</th><th>Answer / guidance</th><th>Marks</th></tr></thead><tbody>'+rows+"</tbody></table></section>"}g("paper").innerHTML='<div class="paper-title">'+(g("school").value.trim()?"<strong>"+esc(g("school").value.trim())+"</strong>":"")+'<h2>'+esc(g("title").value.trim()||"Mathematics Examination")+'</h2><div class="paper-meta"><span>'+g("level").selectedOptions[0].text+"</span><span>"+grade+"</span><span>"+g("duration").value+" minutes</span><span>"+total+' marks</span></div></div><div class="candidate"><span>Name: <span class="line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span>Class: <span class="line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></div><div class="instructions"><h3>Instructions</h3><ol><li>Answer all questions.</li><li>Show all working for Section B.</li><li>Check your answers before submitting.</li></ol></div><h3 class="section-title"><span>Section A: Objective</span><span>'+o+' marks</span></h3><ol class="questions">'+objective+'</ol><h3 class="section-title"><span>Section B: Structured</span><span>'+(s*writtenMarks)+' marks</span></h3><ol class="questions">'+structured+"</ol>"+scheme;g("print").disabled=g("download").disabled=false}
function download(){var lines=[g("school").value,g("title").value,g("level").selectedOptions[0].text+" · "+selectedGrade()+" · "+g("duration").value+" minutes","","SECTION A"];current.objective.forEach(function(item,i){lines.push("A"+(i+1)+". "+item.q+"  "+item.options.join(" | "))});lines.push("","SECTION B");current.structured.forEach(function(item,i){lines.push("B"+(i+1)+". "+item.q)});if(g("scheme").checked){lines.push("","MARKING SCHEME");current.objective.forEach(function(item,i){lines.push("A"+(i+1)+". "+item.a)});current.structured.forEach(function(item,i){lines.push("B"+(i+1)+". "+item.a+" — "+item.e)})}var nl=String.fromCharCode(13)+String.fromCharCode(10),blob=new Blob([lines.join(nl)],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mathematics-exam-paper.txt";a.click();URL.revokeObjectURL(a.href)}
if(g("yearForm")){g("level").onchange=updateTopics;g("yearForm").onchange=updateSyllabusTopics;updateTopics()}if(g("objective")){g("generate").onclick=generate;g("print").onclick=function(){window.print()};g("download").onclick=download}